### PR TITLE
Extraction of Year, Month, Day, Day of Week, and Day of Year updated

### PR DESCRIPTION
**Pull request by socratesk**
File LabResults.R was not extracting the Year, Month, Day, Day of Week, and Day of Year features correctly. So updated the code extract them correctly.

Also removed the features (Date and mydate) from dataframe.

### CODE REVIEW

**Comment by nicklucius** [comment]
@socratesk- Thanks for your contribution! Out of curiosity, could you tell me what was not extracting correctly with Year, Month, etc.? I checked it out but could determine what the problem is. 

Also, we do use the ```Date``` field in the modeling stage, so could you do a commit to put that back in?

**Comment by socratesk** [comment]
@nicklucius: I downloaded the Lab Results file (2ivx-z93u.csv) locally from the URL (https://data.cityofchicago.org/resource/2ivx-z93u.csv) and then tried reading it as regular CSV file using _read.csv_ command. When I did that, the class of feature _Culture.Sample.1.Timestamp_ was read as Factor instead of POSIXct, which has to be converted as String and then to Date before extracting Year, Month, Day etc.

After your message, I tried reading it directly from URL and the class of feature gets converted into POSIXct directly making you to extract Y, M, D directly.

Again it is the business preference - whether we are going to read the Lab Results file every time from URL (or) it will be supplied to us and we we will have to load it from local file system.

Sure, I will revert the code and check-in.

Thanks for looking into it, Nick! Let me dig into this project more and continue to work on it.

Thanks!

**Comment by socratesk** [comment]
@nicklucius: Since there is no difference between the original code and the code the am trying to revert, please close my earlier pull request to bring the code back to where it was originally.

**Comment by nicklucius** [comment]
@socratesk- Thanks for the explanation. Sounds good!

**Pull request closed without merging**
