### PR TITLE
cleanbeachnames2.csv

### PR DESCRIPTION
**Pull request by beckeroobonsai**
This is another variation of cleaning names.  It seemed that the other cleaning was lumping beaches together in a way that caused more duplicate readings for a given beach on a given day.

### CODE REVIEW

**Comment by kbrose** [comment]
Does pull request #54 fix this issue?

**Comment by beckeroobonsai** [comment]
The fix in #54 is similar to what I did with this and the previous pull request, #55 . Only I'm working in Python rather than R.

These two pull requests are necessary together in order to get the function to add on columns of previous days' data to work properly.  Otherwise there wouldn't be unique beach-date records and the merging of new data spuriously added on rows to the data set.  This fixes that for python.

**Comment by kbrose** [comment]
I meant specifically the CSV in #54 - do that updated CSV and this CSV accomplish the same thing?

**Comment by beckeroobonsai** [comment]
The two csv files are quite different.

I want to use Beach-Date as a unique identifier so I spent some time looking at where it was not unique. Without doing any name cleaning, there are 11 records that share Beach-Date.
Using the old cleanbeachnames.csv gave 588 duplicate Beach-Date records (which includes the original 11).  The newer mapping I made gave 110 duplicates. Processes of cleaning names is going to discard some records as duplicates but we should try to minimize the data loss. 

The differences between the files:  
I added some name variants.  When I made read_data_simplified() so it is not using split_sheets() it ended up pulling in more data records than before because it included data from 2002 and 2003.  Some of these records have beach name variations that were not listed in the original mapping from cleanbeachnames.csv.

I took out a bunch of name variants.  There are a lot of mapping over of beach name variants in that csv that are not actually variants in the ecoli data records.  Maybe they are in Drek or other data files?  I'm not sure.  I just wanted to make something minimal that made sense to me so I started name mapping from scratch.  

Probably should be more variants merged together than I currently have, so that more beaches have roughly the same number of records.

**Pull request merged**
