### PR TITLE
Cprok data prep clusters

### PR DESCRIPTION
**Pull request by ChrisProkop**
Beach groupings based on geography.  Seven groups are currently added, with flags of 1 or 0 if it is in the list of beach names for that group.  There is a Meta North Beaches group that is 1 if in the groups North of Navy Pier, and 0 if no (read: is South).

### CODE REVIEW

**Comment by kbrose** [comment]
@ChrisProkop It looks like there's some hard tabs getting mixed in there, could you change those to spaces?

**Comment by ChrisProkop** [comment]
Hi, 

I updated it and pushed it to the remote branch.  Do I have to do another pull request?  Sorry, I don't know what the proper procedure is for this, or if my commit is properly part of this pull request.

-Chris

**Comment by kbrose** [comment]
Nope, the new commit automatically gets added here. You can probably see it in the timeline above (assuming it's 00cc71d)

**Comment by kbrose** [comment]
@ChrisProkop It looks like the variable `south_group` is not used. Is that expected?

**Comment by kbrose** [comment]
I suppose it's just the inverse of the `north_group`, so no need to include it...?

**Comment by ChrisProkop** [comment]
That was my thinking.  That way it is a single variable that has both
factors as part of it.

I need to combine the other six groups into a single factor variable as
well.

**Comment by kbrose** [comment]
That seems reasonable.

Also, you might be interested in the fact that my most recent random forest models assigned high feature importances to the group 2 and group 5 factor variables, and very very low importances to groups 1, 3, 4, and 6 factor variables.

**Comment by ChrisProkop** [comment]
That is very interesting.  2 and 5 are the "middle" of each of the N/S
groups, and I think in both cases are also the largest groups.  Being
largest also comes with the beaches being very close to each-other, which
might explain why those two stick out.

**Pull request merged**
