### PR TITLE
NAs changed to 0

### PR DESCRIPTION
**Pull request by CallinOsborn**
Not much to it, find all the NAs in the 10 columns, and change them to a 0

### CODE REVIEW

**Comment by nicklucius** [comment]
@CallinOsborn These are the lock data fields I'm getting: 

```Wilmette```
```total_volume```
```Obrien.Lock.Open```
```CRCW.Lock.Open```
```Wilmette.Lock.Open```
```Obrien.Lock.Volume```
```CRCW.Lock.Volume```
```Wilmette.Lock.Volume```

It looks like Wilmette's fields are showing up twice--do you get this too?

**Comment by CallinOsborn** [comment]
There are 2 for each on of the locks:
`O.brien` 
`CRCW`
`Wilmette`
 The first data field is how much was dispersed on that specific day (avg. over the whole time the lock was open), the second one is over the whole time how much was dispersed over the whole time it was open.

**Comment by nicklucius** [comment]
OK gotcha. And what is the one ```total_volume``` field?

**Comment by CallinOsborn** [comment]
`total_volume` is the sum of dispersion over the whole time the locks were open for all 3 locks. 

 i.e. If `Wilmette` (270 sq. feet over 3 days),  `CRCW`(140 sq. feet over 3 days), `O.brien`(140 sq. feet over 3 days) are open over the same 3 day period the `total_volume` would be 410.

**Pull request merged**
